### PR TITLE
Fix pantry integration by using a single compressed basket

### PR DESCRIPTION
**Pull request by marcemmers**
This is mainly a quick fix for #237.

I have only tested this for the base functionality on both windows and linux, only with a firefox browser.
No performance tests has been performed to see if we can fit the 5MB in a floppy drive (max basket size is 1.44MB).

Also fixed the packaging script from some permission errors. No idea if that is wanted or not.

### CODE REVIEW

**Comment by Bishop341-B** [comment]
Oh... the task gets some cruise speed XD

It seems to be working ok. The compression approach works very nicely ^^ 

The size gain with compression was better than expected in the preliminary tests. In my current data file: 1,14 MB -> 64 KB, yes, i think we can forget any basket size limitation problem for the moment.

I have some questions:

- Why these modifications in the packagin.sh script?
- You have changed the sync time from 3 min to 1 min? This will not give us problems with pantry and their rate limit when doing constant game refresh, like farming or alike? Have you tested it in those conditions?
 - It seems the time display in log needs to converted here to somewhat more human readable here:
imagen
- The readme.md should be also modified to include the new used lib, and changed number of external used libs from 2 to 3
imagen

Otherwise... very jood job :+1:

**Comment by marcemmers** [comment]
The compression was a good idea indeed. And looking into the data there is a whole bunch of repeating JSON which is what compression algorithms love :D Glad it works so well. Might be a good improvement later on than for the storage of the other data.

As far as your questions go:
* Somehow I ran into some permission issues when running the packager as it was. Since there is an output argument (which defaults to `stdout`) I figured why not just write to output directly.
* The rate limit on pantry is currently 2 calls per second (in their FAQ at least). We make 1 or 2 API calls now per sync which is rate limited to once every 60 seconds with this. I think we should still be safe. But to answer, no I have not tested it apart from running it since I opened the PR.
* Ah yeah that was still a debug leftover. I suppose I might as well just remove it altogether.
* Yep good point, will add it there probably tomorrow.

**Comment by Bishop341-B** [comment]
- Ok keep it then. I guess there will be no problems publishing later, they should not. If they are we can revert then.
-  Ok also to the rate limit. We can merge it and do some testing before next release, maybe you want to do them when you can?
 ;)

Nice. We will merge it when completed.

**Comment by marcemmers** [comment]
Not exactly sure what you mean with "maybe you want to do them when you can"? These changes or the tests or something else? ;)

**Comment by Bishop341-B** [comment]
The tests... XD

Nice. Merging...

**Review by Bishop341-B — APPROVED** [review]
Nice job :+1:

**Pull request merged**
