### PR TITLE
Improvements/lifeform support

### PR DESCRIPTION
**Pull request by ThomasWolf94**
Implemented a basic lifeform support:
production from lfbuildings and lfresearch is now included in all calculations
roi is available for lfresearch with resource production bonus but not included in return on investment tab of overview
total production of planets somehow are a little off for daily and weekly production, can't find out why
the settings for the lifeform boni is fetched from ogame api

### CODE REVIEW

**Comment by Bishop341-B** [comment]
- css changes for the energy color problem in firefox works ok
- the added system switching with up/down arrow in fleet1 works, but the timing information is not getting a refresh, so the main utility for which this change was requested is missing:

imagen
imagen
- the total production of planets i think is a rounding problem, i am investigatin it, i will update on this later

**Comment by roms591** [comment]
Hello @ThomasWolf94 
Are you able to retrieve lifeform bonus for finding ressources in expedition ? 
If yes, is it possible to add this bonus into following lines to calculate the good numbers of cargos necessary for the expedition ? 
 #10958   let maxPT = Math.max(minPT, this.calcNeededShips({ fret: 202, resources: maxTotal  * BONUS}));
 #10959   let maxGT = Math.max(minGT, this.calcNeededShips({ fret: 203, resources: maxTotal *  BONUS}));

If bonus equal to 50% we have to multiplicate by 1.50

Thanks

**Comment by ThomasWolf94** [comment]
> Hello @ThomasWolf94 Are you able to retrieve lifeform bonus for finding ressources in expedition ? If yes, is it possible to add this bonus into following lines to calculate the good numbers of cargos necessary for the expedition ? #10958 let maxPT = Math.max(minPT, this.calcNeededShips({ fret: 202, resources: maxTotal * BONUS})); #10959 let maxGT = Math.max(minGT, this.calcNeededShips({ fret: 203, resources: maxTotal * BONUS}));
> 
> If bonus equal to 50% we have to multiplicate by 1.50
> 
> Thanks

Hey,
should be possible. Do you know if this Bonus is allways global or changes from planet to planet?

**Comment by roms591** [comment]
> > Hello @ThomasWolf94 Are you able to retrieve lifeform bonus for finding ressources in expedition ? If yes, is it possible to add this bonus into following lines to calculate the good numbers of cargos necessary for the expedition ? #10958 let maxPT = Math.max(minPT, this.calcNeededShips({ fret: 202, resources: maxTotal * BONUS})); #10959 let maxGT = Math.max(minGT, this.calcNeededShips({ fret: 203, resources: maxTotal * BONUS}));
> > If bonus equal to 50% we have to multiplicate by 1.50
> > Thanks
> 
> Hey, should be possible. Do you know if this Bonus is allways global or changes from planet to planet?

Hello @ThomasWolf94 

Great news ! The bonus is global

**Review by Bishop341-B — APPROVED** [review]

**Pull request merged**
