### PR TITLE
Improvement: Add PT-BR translate

### PR DESCRIPTION
**Pull request by danton-vicente**
Add PT-BR translate to OG Infinity Extension

### CODE REVIEW

**Comment by Bishop341-B** [comment]
Nice work.

But i have one question. Can we use the same strings also to Portugal portuguese and have only one string set to both?

I mean, we have disscus the matter before on Discord, some portuguese users (of both variations) wants a translation: https://discord.com/channels/735582742435201114/1148927235454140467/1148978407783276584

For us it is desirable to have only one portuguese translation, because it is more easy to maintain. This is the reason because that line was there:

imagen

**Comment by danton-vicente** [comment]
> But i have one question. Can we use the same strings also to Portugal portuguese and have only one string set to both?

I truly believe we cannot. Although the two languages ​​are very similar, we have many changes between pt-br and pt-pt, with words that can generate misinterpretations or errors. I removed the language switch when pt-br to pt-pt for this reason. I understand this point, but the languages ​​are not as similar as the Spanish languages ​​are to each other.

**Comment by Bishop341-B** [comment]
> I truly believe we cannot. Although the two languages ​​are very similar, we have many changes between pt-br and pt-pt, with words that can generate misinterpretations or errors. I removed the language switch when pt-br to pt-pt for this reason. I understand this point, but the languages ​​are not as similar as the Spanish languages ​​are to each other.

Well, you, as a native speaker, know much better than us on the subject ;)

> 
> Maybe we can check with pt-pt users if the translation was good enough or if it caused any problems.

Yep, i think is worth to ask them on Discord. Maybe do you yourself want to ask the users from Portugal/Brazil on the ogi General Discord channel what they think about this? You can mention the changes page of this PR so they can see what are the translations will be used.

**Comment by danton-vicente** [comment]
Message sent:

**Review by Bishop341-B — APPROVED** [review]

**Pull request merged**
