### PR TITLE
Fix/planet list lf icon

### PR DESCRIPTION
**Pull request by cubayy**
Hi,

I fixed the bug with LF icon in planet list.

Before the lifeform type was defined by the name so it didnt work for other language than english.

Now, LF type is an attribute of the planet. It is initialize by passing on any page of the concerned planet.

### CODE REVIEW

**Comment by ThomasWolf94** [comment]
If I see that correctly, you have to revisit every planet after every empire refresh. There should be a better solution to solve that problem. I never had issues so maybe you can tell me on what locale it doesn't work.

**Comment by Bishop341-B** [comment]
> If I see that correctly, you have to revisit every planet after every empire refresh. There should be a better solution to solve that problem. I never had issues so maybe you can tell me on what locale it doesn't work.

It will fail in every locale that have different words for lifeforms. For example, spanish and french:

imagen

Maybe there are many others. Damm GF, why the don't use ids here as in other places? 

To solve spanish and french we can use these translated names introduced in the Discoveries PR in getTranslatedText(), but this method needs complete locales to be activated (all strings). We can not use this method for the other locales. Maybe we can collect the different strings and put this translation texts in the markLifeforms() method.

The other way, and to not visit every planet, there is not any other place where it can be found an association between lifeform ids and locale names?

**Comment by Bishop341-B** [comment]
Also... if i am not wrong: what about with planets that have no lifeform choosen?

imagen

It seems that they will be smashed to "Humans".

**Comment by cubayy** [comment]
> Also... if i am not wrong: what about with planets that have no lifeform choosen?
> 
> imagen
> 
> It seems that they will be smashed to "Humans".

I confirm. Before my fix, all my planet was "Human" instead of "Roctas" in french.

I think it is the easiest fix to this issue. Default = no icon and at the first visit on a planet, icon is initialize and display. 

Maintain all languages seems to be a lot of effort for just an icon, no ?

**Comment by Bishop341-B** [comment]
> 
> I confirm. Before my fix, all my planet was "Human" instead of "Roctas" in french.
> 
> I think it is the easiest fix to this issue. Default = no icon and at the first visit on a planet, icon is initialize and display.
> 
> Maintain all languages seems to be a lot of effort for just an icon, no ?


It is a way to do a fix, and yes, this way we do not need to worry any translations... :+1: 

 **...but what about this way i found just a moment ago that gives us no worries about translations too?**

imagen

In this page seems that we can get an link between lifeform ids and fileform locale names. what if we fetch this page in markLifeforms() and save the lifeform names? This way the fetching for this info must be done only once, and then we have the names to do an right switch (lf). Also, this way we do not have to visit the all the planets to do initialization.

What do you think about this way? Any drawback?

**Comment by cubayy** [comment]
I think it can work. But this page is note very used. For most player, i think they are more chance they will consult all planets before consult this page once.

**Comment by Bishop341-B** [comment]
> I think it can work. But this page is note very used. For most player, i think they are more chance they will consult all planets before consult this page once.

No need to wait to players go to this page or force it. We can always do a background fetch for it -> DOM parsing -> and search the wanted info.

**Comment by cubayy** [comment]
Hi, 

Thank you Bishop, i use your method and it seems to work (At least in .fr, .de and .es) 

It will work on the second refresh for all the planet

**Review by Bishop341-B — APPROVED** [review]
Nice :+1: 

Seems to be working ok.

**Comment by ThomasWolf94** [comment]
Nice, works for me too!

**Review by ThomasWolf94 — APPROVED** [review]

**Pull request merged**
