### PR TITLE
Improvement/return on investment

### PR DESCRIPTION
**Pull request by ThomasWolf94**
### Improved the input with shortcuts
arrow up/down: +/- 1
shift + arrow up/down: +/- 10
ctrl + arrow up/down: +/- 100
k -> *1000
checkInputs() removed, listenKeyboard() adapted

### Expedition and Collect
one button for expedition, can change default ship
one button for collect, can change ship/target and mission
after collection fleet sent, moves to next planet

### Improved control via hotkeys
ctrl + arrow to navigate planets / moons
fleet1 shortkeys:
KeyE: expedition -> fleet2
KeyC: collect -> fleet2
KeyA: all ships
keyM: most ships
KeyN: no ships
enter: -> fleet2
fleet2 shortkeys:
KeyE: expedition
KeyS: espionage
KeyD: deployment
KeyT: transport
KeyH: hold
KeyC: colonisation
KeyR: recycle
KeyX: attack
alt + KeyX: ACS attack
ctrl + KeyX: moon destruction
shift + KeyP: planet
shift + KeyM: moon
shift + KeyD: debris
KeyA: all resources
KeyM: most resources
KeyN: no resources
enter: send fleet

### Planet list
ctr + arrow: navigate planet list
added navigation arrows to navigate planet list

### Improved building/research details
buildings and research improved to calculate costs and times
buildungProduction changed to calculate production with position bonus
data for buildings / research stored in constants BUILDING_INFO and RESEARCH_INFO

### Content
Lifeform building / research progress details
better classification of flying fleet
overview of transported resources as tooltip for flying fleet icon
changed icons to fit ships / defense and also fit with lifeforms
tooltips for numbers
storage timers like in AntigameReborn

### Improved Missing Lock
changed to also work if you add multiple buildings

### Technology details
also demolishment is now displayed correctly
shows amortisation time for mines, plasma and astro
small solar satellite icon with number of needed sats is shown for mines and research

### Fleetdispatcher
needed ships for transport if no ships on planet/moon
target highlighting
collect button and expedition buttons changed
fleet2 remove handles and rappers and add overview of selected ships
adaption for lifeforms(added food resource)
fixed problem with planet specific kept ships

### Overview
mines overview shows storage fill times as tooltip
fleet/defence overviews now links to moons if moons selected

### Statistics
general stats improved (storage level needed for daily production as tooltip, transport capacity)
new production overview
added return on investment (roi) tab to statistics (currently no lifeforms)

### List of changes to data structure
removed:
- this.json.apiTechData
- this.json.ptFret
- this.json.gtFret
- this.json.pfFret
- this.json.cyFret
- this.json.pbFret
- this.json.myMines
- this.json.lastResUpdate
- this.json.myRes
- this.json.tech114
- this.json.tech113
- this.json.tech122
- this.json.tech124
- this.json.tech108
added:
- this.technocrat
- this.admiral
- this.engineer
- this.allOfficers
- this.current.id
- this.json.technology
- this.json.ships
- this.json.allianceClass
- this.json.productionProgress
- this.json.lfProductionProgress
- this.json.researchProgress
- this.json.lfResearchProgress
- this.json.needSync
- this.json.flying.ids
- this.json.options.collect
- this.json.options.maxCrawler
- this.json.options.crawlerPercent
- this.json.options.tradeRate

### CODE REVIEW

**Comment by Bishop341-B** [comment]
Hi.

It is a huuuge PR. **Fantastic job**, with many useful features. I personally love the new profitability and production section. And the localization job. ;)

I only done a first contact preliminar loose review, but i saw already a few details to begin to comment:

- The dialogs (options, stats, overview/empire stats, direct links, empire data loading indicator...) now appears in the top of the window. I think that the previous position centered on window was more useful as event box was visible after the dialog and more ergonomic, especially for the shortcuts in the fleet page. Maybe also prettier, but this a personal opinion.
image

- Some cosmetic adjustments to be adressed:
    -  in fleet page:
image
    - in construction/research/shipyard/... the ? is in another color, with low contrast with background:
image
    - human lifeform do not get icon in planet list:
image
    - the new flying details tooltip is **great**, but with large accounts with many planets, the tooltip appear to bottom, largely not visible, and makes the user must scroll to see it. can be it appear to up, instead?
image
    - with large accounts with many ships, new stats bottomline gets too full XD
image

- In firefox, i get an error in fleet page and i can not go further:
image
image

- Seems that the new production section tab in stats needs to going through some pages (resources?), clicking tab before doing it gives an error in console and crash the dialog. Can not take the mines data directly from the empire data (if is this data what it needs)?

- I see in the code that some last version 2.2.8 changes are not applied. This, for example, maybe anothers, the one that fixes planets flights activity for ACS fleets:

image
image

Please, can you ensure that all the fixes for this version are applied? Or maybe someones not needed because some changes you made in the code?

Well that is enough for the moment ;)

Maybe we can have more easy talk about these and another details if you came to discord and talk with the dev team. Do you want to join the dev team? If yes, ask directly to Aleks#4097

Great job.

**Comment by ThomasWolf94** [comment]
Hey,

i know it's not a small change at a time like it should be. I used AGR, but when RIV stopped maintaining it I switched to OgameInfinity. I soon realised that i missed some features and startet to implement them for my needs. So over time the changes added up and I decided to integrate the ROI calculations. Now I was thinking it would be nice to share my work with the community, that's why I integrated it into the latest version over the last week. When I pulled the master it was just before 2.2.8 was online, so I might have missed those changes.

I currently don't play on any universe with lifeforms, so my testing is now limited. The fleet page should be adapted for lifeforms, did it back then when I played the beta and maybe some things have changed.
The position of the dialogue window is personal preference, but I did it for the overview and settings, to have the different tabs on the same place. Maybe we could talk on Discord about the topic and decide, what would be best.

Some other points you made are quickly resolved, I don't have time this weekend but maybe I get to it next week. I would join the dev team, but then I need some more info about how the codebase is managed.

**Comment by Bishop341-B** [comment]
Great ;)

We wait you in the OGI discord. Please, ask Aleks for access to the dev section.

Thanks for the new commits. The merge is near ^^

 A few more things i saw to get adressed:

- A similar above getSeparator() error that i got in firefox entering fleet page, i get it **also in chrome**, in the same account. It is a **.es** server. I do not get the error in Belinda, that is a **.en** server. Maybe there is a locale problem in this function.
imagen


- There are a few innerHTML assignments in the code that needs to be changed to use .html() to pass through DOMPurify, mainly the ones that the assign are different to "". Basically this is an "recommendation" of the mozilla add-on review team to get a validated new release. Yes, i know... ¬¬ U
imagen


- The commit you make to get dialogs centered, but Stats and Overview top aligned, works great in **chrome**, but it seems does not work 100% in **firefox**: Stats and Overview also get centered. Also, for **firefox**, in Stats i get no resource icons in all tabs except Production, and sometimes an error. In Overview, i get an error every time.

Stats:
imagen
imagen

Overview:
imagen

**Review by SKiiDROW — APPROVED** [review]

**Comment by ONeill33** [comment]
The discord invitation link is here : https://discord.gg/99TnejZx

**Comment by Bishop341-B** [comment]
I see your last commit with various fixes. Good job ^^

But, the locale fix of getSeparator() does not work 100%, because it is returning "" as a group separator for my locale and is ".". Thus cargo space, for example, is not computed correctly and gives NaN in various places.

**I think that it seems more easy and simple to just use LocalizationStrings for this**:

imagen

I am testing it with this change and seems to be working ok.

I have an idea. We can merge this PR in a separate temporary branch in the OGI repo. Doing this, more people from the dev team can do commits directly to this branch to help bugfixing the few remaining issues, add little improvements, localization strings... Then, when it is ready, merge to main branch with a PR and then do a new release. The only drawback is that **you must have dev access to the OGI repo to do the same in a comfortable way**. If not, then you have to do another PR to this separate branch from your fork repo.

Please, ask Aleks in discord to give you access to the OGI repo. And to the dev section of the OGI discord. We can then continue talking there more easyly.

**Comment by ThomasWolf94** [comment]
Yeah the localization is a little strange. Some of the locale don't have group separators but OGame uses one. Back in the Lifeform Beta they used the same separator for decimal and thousands, that's why I changed it.
Most of the other things should work fine now. I still use the empire info to get the stats, but have guards to prevent errors.
The dialog position fix is done with the selector :has(*), from the main browsers only Firefox doesn't support it. If that is a problem, we can also add classes in JS but I can't fix it only in CSS.
We can create a temporary branch, I already contacted Aleks on Discord, but haven't gotten a response so far.

**Comment by Bishop341-B** [comment]
Yes, i see. I think that is not a serious problem. We can leave it as is. As it is already with experimental support in firefox, the day it is fully supported, it will work properly.

I already do a ping to Aleks. I hope is not too away...

**Comment by Bishop341-B** [comment]
Aleks seems to be away... 

Change of mind, I'm going to try the merge directly to the master branch. Until Aleks shows up and gives you access to the repo, for more changes you will have to open more PRs, sorry.

**Review by Bishop341-B — APPROVED** [review]

**Comment by ThomasWolf94** [comment]
Okay, thank you. I already fixed most of the issues, just let me know if you find anything else. You can also contact me in Discord (Wolfswelpe#0197).

**Pull request merged**
