### PR TITLE
Fix error on Simulator page

### PR DESCRIPTION
**Pull request by baiiko**

### CODE REVIEW

**Comment by Bishop341-B** [comment]
Hi, thanks for you fix ;)

But i am thinking maybe it is better to put that specific page exclusion in another place, here:

image

...where we have already another specific page exclusion and keep them together. We can also then add  "empire" page that need to be excluded also.

Maybe we can replace that line with something like this:

`if (["intro", "empire", "combatsim"].includes(this.page)) return;`

What do you think?

**Comment by baiiko** [comment]
Yes i can !

**Comment by baiiko** [comment]
@Bishop341-B It's done.

**Comment by Bishop341-B** [comment]
> @Bishop341-B It's done.

Uhmm... it does not work the way i thought. It crash earlier in the constructor. For the "intro" page it works, but is does not with the "empire" and "combatsim". Then it is better place where you put it the first time, sorry.

Maybe something like that, with nice debug loggin: 

image

```
const rawURL = new URL(window.location.href);
const page = rawURL.searchParams.get("component") || rawURL.searchParams.get("page");
if (["intro", "empire", "combatsim"].includes(page)) {
  logger.info("Excluded page: " + page);
  return;
}
```

**Review by Bishop341-B — APPROVED** [review]

**Comment by Bishop341-B** [comment]
Seems to work nicely

**Pull request merged**
