### PR TITLE
Turkish language option added.

### PR DESCRIPTION
**Pull request by devrimmehmet**

### CODE REVIEW

**Review by Bishop341-B — APPROVED** [review]
imagen

This added /*  in line 16237 has to be removed. Otherwise good job :+1: 

Please, just make another commit removing this line in your repository and the change will get pushed to here, no need to do another PR ;)

**Comment by devrimmehmet** [comment]
yes dude i think i finally did it :)

**Comment by Bishop341-B** [comment]
Hi, we need your help for another PR we are preparing also for merge, there some additional strings to translate. Please, could you give a look to the translations below? Are they ok? Or you may tell us what other translation you think is more suitable ;)

"Lifeforms" -> "Yaşam formları"
"Default expedition time" -> "Varsayılan sefer süresi"
"Indicate finished process" -> "Bitmiş süreci belirtin"
"External Tools" -> "Harici Araçlar"
"Default missions" -> "Varsayılan görevler"

**Comment by devrimmehmet** [comment]
they are quite appropriate, but I think the following two should change like this, but if I see where they are used, maybe I can interpret it differently.

"Indicate finished process" -> "Bitmiş İşlem"
"External Tools" -> "Diğer Araçlar"

**Comment by Bishop341-B** [comment]
> they are quite appropriate, but I think the following two should change like this, but if I see where they are used, maybe I can interpret it differently.
> 
> "Indicate finished process" -> "Bitmiş İşlem" "External Tools" -> "Diğer Araçlar"

Of course... "External Tools" is to be used in the settings:

imagen

The other one i do not know... maybe it is a future feature or a improvement that @ThomasWolf94 has planned to do.

**Comment by devrimmehmet** [comment]
"Indicate finished process" -> "Tamamlanmış Görevler"

Finally, I think we should do this as well.

**Comment by devrimmehmet** [comment]
"Lifeforms" -> "Canlı Türleri"
"Default expedition time" -> "Varsayılan keşif süresi"
"Indicate finished process" -> "Tamamlanmış işlemi belirt" 
"External Tools" -> "Diğer Araçlar"
"Default missions" -> "Tamamlanmış Görevler"

**Comment by Bishop341-B** [comment]
> "Lifeforms" -> "Canlı Türleri" "Default expedition time" -> "Varsayılan keşif süresi" "Indicate finished process" -> "Tamamlanmış işlemi belirt" "External Tools" -> "Diğer Araçlar" "Default missions" -> "Tamamlanmış Görevler"

Ok, we will use these translations. Thanks ;)

**Comment by Bishop341-B** [comment]
The PR has been merged and will be in the next release :+1: 

By the way, maybe do you want to join the dev team? If you are interested, please, ask to @alexisfasquel via PM in discord (@Aleks).

**Pull request merged**
