### PR TITLE
Add discoveries statistics

### PR DESCRIPTION
**Pull request by cubayy**
Add discoveries statistics - independant from expeditions statistics

- LF discoveries are not reported in "Object" and "Fleet" into Expedition statistics anymore
 - Additional color is added to "Expedition" messages to treat these cases : Artefact found (Yellow), Discovery of Human, Discovery of Rock'tal, Discovery of Mechas, Discovery of Kaelesh (Color based on LF technologies graphics chart)
 - A new tab is added in statistics to show Discoveries statistic (Exeperience and Artefacts) like Expedition statistics (only if it is an LF universe)

For the formating, "npm run format" change all the file, so i present you an hand-formatted version

  I am a newbie in JS so i take all your advices ;)

### CODE REVIEW

**Comment by Bishop341-B** [comment]
Looks great. Very nice indeed.  :)

I made a little test and seems to be working ok.

I have one suggestion. Maybe there are more convenient to put the Discoveries tab between Combats and Profitability, or maybe between Expeditions and Combats.

And one question, what is this (the pointer area) for?

imagen

Maybe do you want to join the dev team? There is a lot of work to do... XD

**Comment by Bishop341-B** [comment]
Ahh... for the format issue, did you check it is using the format rules for prettier in .prettierrc? Anyway, maybe you can run prettier in the web vscode that is built-in in github.

**Review by Bishop341-B — APPROVED** [review]
Did you tested that regular expeditions work fine after the changes?

Some little cosmetic to fix:

imagen

**Comment by cubayy** [comment]
>  I have one suggestion. Maybe there are more convenient to put the Discoveries tab between Combats and Profitability, or maybe between Expeditions and Combats.

Ok i move it between Expéditions and Combats

> And one question, what is this (the pointer area) for?

I didnt know how to show artefacts loots. I didnt want to mix them with experience stats and i didnt want to repeat the "Artefacts" title on the column.

Maybe should i make another box without line title and with 4 columns : Metal, crystal, deut spent in discoveries + 1 column for artefacts. Do you think it is a better solution ?

>Did you tested that regular expeditions work fine after the changes?
  Yes it does. But i test it only in french language. Do you have some tips to test it on other languages ?

**Comment by Bishop341-B** [comment]
> I didnt know how to show artefacts loots. I didnt want to mix them with experience stats and i didnt want to repeat the "Artefacts" title on the column.
> 
> Maybe should i make another box without line title and with 4 columns : Metal, crystal, deut spent in discoveries + 1 column for artefacts. Do you think it is a better solution ?

imagen

In this one, the total line for each lifeform gets no use for experience (is the same as experience line) or for artefacts, right?

Yes, maybe two boxes, one for artefacts and one for experience are better. Only one line for "Experience" in the experience box and the other box that you described for artefacts

> > Did you tested that regular expeditions work fine after the changes?
> 
> Yes it does. But i test it only in french language. Do you have some tips to test it on other languages ?

The changes you made seems to not have locale dependencies, have they?

> I can help you an other dev if you need. But as i said, i am a beginner in JS (First time i touch it for 7 years :D )

Any help is welcomed ;)

I ping @alexisfasquel  for this.

**Comment by cubayy** [comment]
The modifications are up :
image

I corrected all your point. 

>The changes you made seems to not have locale dependencies, have they?
I extract the experience from Expedition messages. Number of experience is followed by an "&nbsp" character. I think it's the case for all language but i cant test this. (For artefacts number, the extraction was already done and puted in Fleet stats from Expedition)

**Comment by Bishop341-B** [comment]
> The modifications are up : image
> 

Looks great :+1: 

> I extract the experience from Expedition messages. Number of experience is followed by an "&nbsp" character. I think it's the case for all language but i cant test this. (For artefacts number, the extraction was already done and puted in Fleet stats from Expedition)

Maybe you can use our functions toFormatedNumber(value, precision = null, units = false) and fromFormatedNumber(value, int = false) to show and extract values in the same way they are used in the expedition stats, to show and extract values. This way we get a unified locale behaviour.

**Comment by cubayy** [comment]
I am not sure to understand. I already use toFormatedNumber in the boxes 
image

I have the same format for expedition : 
image

Do i forget it somewhere?

**Comment by Bishop341-B** [comment]
> I am not sure to understand. I already use toFormatedNumber in the boxes
> I have the same format for expedition 
>  Do i forget it somewhere?

Ohh... sorry if a do not have expressed better, I was talking about in a general way about using these functions for the Discovery stats in the same way are used in Expedition stats. I did not check for if you have used toFormatedNumber or fromFormatedNumber in every place XD. My comment was in response for your comment about the extraction values for Discovery stats.

**Comment by ThomasWolf94** [comment]
image
Very nice job, just tried it on my new LF account.
If there is no current Data the formatting seems a little bit off, maybe this can be fixed.

**Comment by cubayy** [comment]
> image Very nice job, just tried it on my new LF account. If there is no current Data the formatting seems a little bit off, maybe this can be fixed.

Do you have update the CSS since the "Discoveries stats boxes modification" commit ? 

I changed the boxes format (5 colums -> 4 columns). I created an new german account and it seems to work 
image

**Comment by ThomasWolf94** [comment]
Opera Snapshot_2023-03-30_221936_s192-de ogame gameforge com
Now it's even worse, did you test it on chromium browser?

**Review by ThomasWolf94 — APPROVED** [review]

**Pull request merged**
